spring:
  application:
    name: "Survey Mate API"

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/surveymate?allowPublicKeyRetrieval=true&useSSL=false
    username: survey_user
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 10MB

  config:
    import: "optional:file:.env[.properties]"

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

file:
  upload:
    member-profile: uploads/member/profile

logging:
  level:
    root: ERROR
    com:
      surveymate: DEBUG
    org:
      springframework:
        web: ERROR
        transaction: ERROR
      hibernate:
        SQL: TRACE
        orm:
          jdbc:
            bind: TRACE
        type:
          descriptor:
            sql:
              BasicBinder: TRACE


